
package com.mycompany.sistemacreditos;

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearClienteBtn = new javax.swing.JButton();
        cobrarCuotaBtn = new javax.swing.JButton();
        listadoClientesBtn = new javax.swing.JButton();
        generarCreditoBtn = new javax.swing.JButton();
        calculadoraBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearClienteBtn.setText("CREAR CLIENTE");
        crearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(crearClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 126, 148, 72));

        cobrarCuotaBtn.setText("COBRAR CUOTA");
        getContentPane().add(cobrarCuotaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 123, 160, 80));

        listadoClientesBtn.setText("LISTADO CLIENTES");
        getContentPane().add(listadoClientesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 148, 65));

        generarCreditoBtn.setText("GENERAR CREDITO");
        getContentPane().add(generarCreditoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 160, 65));

        calculadoraBtn.setText("CALCULADORA");
        getContentPane().add(calculadoraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 126, 153, 72));

        salirBtn.setText("SALIR");
        getContentPane().add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 115, 43));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA CREDITOS - DEPORTES 7");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBtnActionPerformed
      FormCrearCliente nuevaVentana = new FormCrearCliente();
      nuevaVentana.setVisible(true);      
    }//GEN-LAST:event_crearClienteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculadoraBtn;
    private javax.swing.JButton cobrarCuotaBtn;
    private javax.swing.JButton crearClienteBtn;
    private javax.swing.JButton generarCreditoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listadoClientesBtn;
    private javax.swing.JButton salirBtn;
    // End of variables declaration//GEN-END:variables
}
